### ISSUE TITLE
selection color in text files in base16-nord

### ISSUE THREAD

**Issue by euglevi** [arbennett/jupyterlab-themes#13]
First of all, thank you for your work. I really like the theme.

This time the base16-nord installation went fine, but an issue still persists. In text files (I use both .txt and .do) sometimes when you select a slice of text you do not see a different color highlighting it. Is it because the selection color is the same as the background color?

**Comment by euglevi** [comment]
This could be solved by changing the `--jp-editor-selected-focused-background` in the variables.css file.

**Comment by xukai92** [comment]
Changing it to `--jp-editor-selected-focused-background: var(--jp-layout-color2);` makes things consistent.

**Comment by arbennett** [comment]
This should be fixed now! Thanks @xukai92 for the solution!
