### ISSUE TITLE
is not a valid npm package

### ISSUE THREAD

**Issue by cnjackhu** [arbennett/jupyterlab-themes#21]
(pt-gpu) hu@ecume:~$ jupyter labextension install base16-mexico-light
An error occured.
ValueError: "base16-mexico-light" is not a valid npm package
See the log file for details:  /tmp/jupyterlab-debug-kcpnj0zk.log

how to solve this?

**Comment by arbennett** [comment]
Hi @cnjackhu - you should be able to install with `jupyter labextension install @arbennett/base16-mexico-light`. Does this work for you?

**Comment by cnjackhu** [comment]
thanks,it is ok now, do you hnow how to make different theme in Terminal?
![image](https://user-images.githubusercontent.com/34678054/92307252-37968b80-ef95-11ea-97c0-11dae736b4e6.png)
Here if I select Jupyter Theme - base16-mexico-light, it will apply to the whole jupyter lab.
And if I point to Terminal Theme- It only has the selection: Inherit, light,dark

**Comment by arbennett** [comment]
This doesn't actually implement new terminal themes, but you can choose inherit to get the right background and main text color. Since we've resolved your original question I'm going to close this issue. Feel free to open more issues if you have troubles!
