### ISSUE TITLE
Look forward to upgrading the projects.

### ISSUE THREAD

**Issue by chenyulue** [arbennett/jupyterlab-themes#33]
Hi, Jupyterlab 3.0 has been released. Look forward to upgrading the projects since when I upgrade jupyter lab to 3.0, all the theme are out-of-date.

**Comment by sujaybokil** [comment]
No issues, just waiting for the themes to support Jupyterlab 3.0. Is there any kind of tentative date by which we can expect the themes to be ready with Jupyterlab 3.0 support?

**Comment by arbennett** [comment]
@chenyulue and @sujaybokil  - I just pushed updates that should work for Jupyterlab 3! It's just a quick version/dependency update that doesn't fix or change anything else. Let me know it this works!

**Comment by chenyulue** [comment]
@arbennett Thanks! The themes installed in my computer works well.

**Comment by arbennett** [comment]
Excellent - I'm going to close this for the moment, but there are still some new upgrades I'd like to accomplish (see #34). Feel free to reopen if you run into any issues!
