### ISSUE TITLE
Support JupyterLab 1.x.x

### ISSUE THREAD

**Issue by cenkt** [arbennett/jupyterlab-themes#4]
Great Job..... However does not build in  JupyterLab 1.2.6 with message:

> Extension Installation Error
> An error occurred installing @arbennett/base16-solarized-dark.
> 
> Error message:
> 
> No version of @arbennett/base16-solarized-dark could be found that is compatible with the current version of JupyterLab. However, it seems to support a new version of JupyterLab. Consider upgrading JupyterLab.
> 
> Conflicting Dependencies:
> JupyterLab              Extension      Package
> >=1.2.1 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/application
> >=1.2.1 <1.3.0          >=2.0.0 <3.0.0 @jupyterlab/apputils

**Comment by arbennett** [comment]
Hi @cenkt - thanks for submitting this issue! I have just started working on this project and it is definitely not polished in any way. So far I am only targeting JupyterLab 2.0.0 and above, but it might simply be possible to change the version dependencies in the `package.json` files of each of the submodules.

**Comment by cenkt** [comment]
Hi @arbennett Was able to "conda uninstall jupyterlab" and "conda install conda-forge jupyterlab" version 2.1.0 and every thing is fine. Thnks once again. Just a small commnet: solarized light colors are a bit off compared to the original. I think they are a bit high on saturation.
Again great job thanks one more time.

https://ethanschoonover.com/solarized/

**Comment by arbennett** [comment]
Thanks for following up! I've also noticed this for both the solarized light colors and the gruvbox light colors. I've created #5 to track progress on them.

Also, I'm going to change this to general support for JupyterLab 1.x.x

**Comment by cenkt** [comment]
👍🙏

Sent from my iPhone

On Apr 16, 2020, at 19:19, Andrew Bennett <notifications@github.com> wrote:

﻿

Thanks for following up! I've also noticed this for both the solarized light colors and the gruvbox light colors. I've created #5<https://github.com/arbennett/jupyterlab-themes/issues/5> to track progress on them.

Also, I'm going to change this to general support for JupyterLab 1.x.x

**Comment by cenkt** [comment]
hi @arbennett were you able to publish the JupyterLab 1.x.x support?

**Comment by arbennett** [comment]
I _think_ thsi should work for juptyerlab 1.x.x now - could you verify @cenkt - using the npm installs?
