### ISSUE TITLE
Solarized light and gruvbox light appear too bright

### ISSUE THREAD

**Issue by arbennett** [arbennett/jupyterlab-themes#5]

**Comment by arbennett** [comment]
I've tried a couple of ways of updating this @cenkt, would you be willing/able to try these out?

**Comment by cenkt** [comment]
@arbennett I have tried to build it locally from the repo with npm but got several errors. One was "the OS is now darwin and linux"
So I was not successful. Can you update the "https://www.npmjs.com/"

**Comment by arbennett** [comment]
@cenkt  - I've pushed updated versions to npm, you should be able to install them and test out whenever you have time. Thanks!

**Comment by cenkt** [comment]
Will get back to you asap

Sent from my iPhone

On Apr 20, 2020, at 08:03, Andrew Bennett <notifications@github.com> wrote:

﻿

@cenkt<https://github.com/cenkt> - I've pushed updated versions to npm, you should be able to install them and test out whenever you have time. Thanks!

**Comment by cenkt** [comment]
Unfortunately I have uninstalled and reinstalled the extension. It shows on the `jupyter labextension list` command, but does not show on the drop down menu. Am I doing something wrong?
```
labextension uninstall  @arbennett/base16-solarized-light
labextension install  @arbennett/base16-solarized-light
```
I also tried in the app but no luck there as well.

**Comment by cenkt** [comment]
I was finaly able to install and test. The colors for Solarized Light are OK now. But the theme ends up showing at a decreased zoom level than the other standard themes. Best

**Comment by arbennett** [comment]
Sorry for the delay here - I'll create a new issue for the zoom level. Out of curiosity, did you install locally or from npm?

**Comment by cenkt** [comment]
from npm... I am not that experienced in node and npm for local instalation.

**Comment by arbennett** [comment]
Seems this is fixed.
